// Mock data for district budget information
export const districtData = {
  "2023": [
    {
      id: "viana-do-castelo",
      name: "Viana do Castelo",
      received: 0.68,
      contributed: 0.52,
      expended: 0.65,
    },
    {
      id: "braga",
      name: "Braga",
      received: 1.45,
      contributed: 1.62,
      expended: 1.38,
    },
    {
      id: "vila-real",
      name: "Vila Real",
      received: 0.72,
      contributed: 0.48,
      expended: 0.7,
    },
    {
      id: "braganca",
      name: "Bragança",
      received: 0.58,
      contributed: 0.32,
      expended: 0.56,
    },
    {
      id: "porto",
      name: "Porto",
      received: 3.25,
      contributed: 3.85,
      expended: 3.18,
    },
    {
      id: "aveiro",
      name: "Aveiro",
      received: 1.32,
      contributed: 1.58,
      expended: 1.28,
    },
    {
      id: "viseu",
      name: "Viseu",
      received: 0.92,
      contributed: 0.78,
      expended: 0.9,
    },
    {
      id: "guarda",
      name: "Guarda",
      received: 0.54,
      contributed: 0.38,
      expended: 0.52,
    },
    {
      id: "coimbra",
      name: "Coimbra",
      received: 1.18,
      contributed: 1.05,
      expended: 1.15,
    },
    {
      id: "castelo-branco",
      name: "Castelo Branco",
      received: 0.62,
      contributed: 0.45,
      expended: 0.6,
    },
    {
      id: "leiria",
      name: "Leiria",
      received: 0.98,
      contributed: 1.12,
      expended: 0.95,
    },
    {
      id: "santarem",
      name: "Santarém",
      received: 0.88,
      contributed: 0.92,
      expended: 0.85,
    },
    {
      id: "portalegre",
      name: "Portalegre",
      received: 0.48,
      contributed: 0.32,
      expended: 0.46,
    },
    {
      id: "lisboa",
      name: "Lisboa",
      received: 4.85,
      contributed: 5.65,
      expended: 4.72,
    },
    {
      id: "setubal",
      name: "Setúbal",
      received: 1.68,
      contributed: 1.85,
      expended: 1.62,
    },
    {
      id: "evora",
      name: "Évora",
      received: 0.58,
      contributed: 0.42,
      expended: 0.56,
    },
    {
      id: "beja",
      name: "Beja",
      received: 0.52,
      contributed: 0.38,
      expended: 0.5,
    },
    {
      id: "faro",
      name: "Faro",
      received: 1.25,
      contributed: 1.42,
      expended: 1.2,
    },
  ],
  "2022": [
    {
      id: "viana-do-castelo",
      name: "Viana do Castelo",
      received: 0.65,
      contributed: 0.5,
      expended: 0.62,
    },
    {
      id: "braga",
      name: "Braga",
      received: 1.38,
      contributed: 1.55,
      expended: 1.32,
    },
    {
      id: "vila-real",
      name: "Vila Real",
      received: 0.68,
      contributed: 0.45,
      expended: 0.66,
    },
    {
      id: "braganca",
      name: "Bragança",
      received: 0.55,
      contributed: 0.3,
      expended: 0.53,
    },
    {
      id: "porto",
      name: "Porto",
      received: 3.1,
      contributed: 3.7,
      expended: 3.05,
    },
    {
      id: "aveiro",
      name: "Aveiro",
      received: 1.28,
      contributed: 1.52,
      expended: 1.24,
    },
    {
      id: "viseu",
      name: "Viseu",
      received: 0.88,
      contributed: 0.75,
      expended: 0.86,
    },
    {
      id: "guarda",
      name: "Guarda",
      received: 0.52,
      contributed: 0.36,
      expended: 0.5,
    },
    {
      id: "coimbra",
      name: "Coimbra",
      received: 1.12,
      contributed: 1.0,
      expended: 1.1,
    },
    {
      id: "castelo-branco",
      name: "Castelo Branco",
      received: 0.58,
      contributed: 0.42,
      expended: 0.56,
    },
    {
      id: "leiria",
      name: "Leiria",
      received: 0.94,
      contributed: 1.08,
      expended: 0.92,
    },
    {
      id: "santarem",
      name: "Santarém",
      received: 0.84,
      contributed: 0.88,
      expended: 0.82,
    },
    {
      id: "portalegre",
      name: "Portalegre",
      received: 0.45,
      contributed: 0.3,
      expended: 0.43,
    },
    {
      id: "lisboa",
      name: "Lisboa",
      received: 4.65,
      contributed: 5.45,
      expended: 4.58,
    },
    {
      id: "setubal",
      name: "Setúbal",
      received: 1.62,
      contributed: 1.78,
      expended: 1.58,
    },
    {
      id: "evora",
      name: "Évora",
      received: 0.55,
      contributed: 0.4,
      expended: 0.53,
    },
    {
      id: "beja",
      name: "Beja",
      received: 0.5,
      contributed: 0.36,
      expended: 0.48,
    },
    {
      id: "faro",
      name: "Faro",
      received: 1.2,
      contributed: 1.38,
      expended: 1.16,
    },
  ],
  "2021": [
    {
      id: "viana-do-castelo",
      name: "Viana do Castelo",
      received: 0.62,
      contributed: 0.48,
      expended: 0.6,
    },
    {
      id: "braga",
      name: "Braga",
      received: 1.32,
      contributed: 1.48,
      expended: 1.28,
    },
    {
      id: "vila-real",
      name: "Vila Real",
      received: 0.65,
      contributed: 0.42,
      expended: 0.63,
    },
    {
      id: "braganca",
      name: "Bragança",
      received: 0.52,
      contributed: 0.28,
      expended: 0.5,
    },
    {
      id: "porto",
      name: "Porto",
      received: 2.95,
      contributed: 3.55,
      expended: 2.9,
    },
    {
      id: "aveiro",
      name: "Aveiro",
      received: 1.22,
      contributed: 1.45,
      expended: 1.18,
    },
    {
      id: "viseu",
      name: "Viseu",
      received: 0.84,
      contributed: 0.72,
      expended: 0.82,
    },
    {
      id: "guarda",
      name: "Guarda",
      received: 0.48,
      contributed: 0.34,
      expended: 0.46,
    },
    {
      id: "coimbra",
      name: "Coimbra",
      received: 1.08,
      contributed: 0.95,
      expended: 1.05,
    },
    {
      id: "castelo-branco",
      name: "Castelo Branco",
      received: 0.55,
      contributed: 0.4,
      expended: 0.53,
    },
    {
      id: "leiria",
      name: "Leiria",
      received: 0.9,
      contributed: 1.02,
      expended: 0.88,
    },
    {
      id: "santarem",
      name: "Santarém",
      received: 0.8,
      contributed: 0.84,
      expended: 0.78,
    },
    {
      id: "portalegre",
      name: "Portalegre",
      received: 0.42,
      contributed: 0.28,
      expended: 0.4,
    },
    {
      id: "lisboa",
      name: "Lisboa",
      received: 4.45,
      contributed: 5.25,
      expended: 4.38,
    },
    {
      id: "setubal",
      name: "Setúbal",
      received: 1.55,
      contributed: 1.7,
      expended: 1.52,
    },
    {
      id: "evora",
      name: "Évora",
      received: 0.52,
      contributed: 0.38,
      expended: 0.5,
    },
    {
      id: "beja",
      name: "Beja",
      received: 0.48,
      contributed: 0.34,
      expended: 0.46,
    },
    {
      id: "faro",
      name: "Faro",
      received: 1.15,
      contributed: 1.32,
      expended: 1.12,
    },
  ],
  "2020": [
    {
      id: "viana-do-castelo",
      name: "Viana do Castelo",
      received: 0.6,
      contributed: 0.46,
      expended: 0.58,
    },
    {
      id: "braga",
      name: "Braga",
      received: 1.28,
      contributed: 1.42,
      expended: 1.25,
    },
    {
      id: "vila-real",
      name: "Vila Real",
      received: 0.62,
      contributed: 0.4,
      expended: 0.6,
    },
    {
      id: "braganca",
      name: "Bragança",
      received: 0.5,
      contributed: 0.26,
      expended: 0.48,
    },
    {
      id: "porto",
      name: "Porto",
      received: 2.85,
      contributed: 3.4,
      expended: 2.8,
    },
    {
      id: "aveiro",
      name: "Aveiro",
      received: 1.18,
      contributed: 1.38,
      expended: 1.15,
    },
    {
      id: "viseu",
      name: "Viseu",
      received: 0.8,
      contributed: 0.68,
      expended: 0.78,
    },
    {
      id: "guarda",
      name: "Guarda",
      received: 0.46,
      contributed: 0.32,
      expended: 0.44,
    },
    {
      id: "coimbra",
      name: "Coimbra",
      received: 1.05,
      contributed: 0.92,
      expended: 1.02,
    },
    {
      id: "castelo-branco",
      name: "Castelo Branco",
      received: 0.52,
      contributed: 0.38,
      expended: 0.5,
    },
    {
      id: "leiria",
      name: "Leiria",
      received: 0.86,
      contributed: 0.98,
      expended: 0.84,
    },
    {
      id: "santarem",
      name: "Santarém",
      received: 0.76,
      contributed: 0.8,
      expended: 0.74,
    },
    {
      id: "portalegre",
      name: "Portalegre",
      received: 0.4,
      contributed: 0.26,
      expended: 0.38,
    },
    {
      id: "lisboa",
      name: "Lisboa",
      received: 4.25,
      contributed: 5.05,
      expended: 4.18,
    },
    {
      id: "setubal",
      name: "Setúbal",
      received: 1.48,
      contributed: 1.62,
      expended: 1.45,
    },
    {
      id: "evora",
      name: "Évora",
      received: 0.5,
      contributed: 0.36,
      expended: 0.48,
    },
    {
      id: "beja",
      name: "Beja",
      received: 0.46,
      contributed: 0.32,
      expended: 0.44,
    },
    {
      id: "faro",
      name: "Faro",
      received: 1.1,
      contributed: 1.26,
      expended: 1.08,
    },
  ],
  "2019": [
    {
      id: "viana-do-castelo",
      name: "Viana do Castelo",
      received: 0.58,
      contributed: 0.44,
      expended: 0.56,
    },
    {
      id: "braga",
      name: "Braga",
      received: 1.24,
      contributed: 1.38,
      expended: 1.22,
    },
    {
      id: "vila-real",
      name: "Vila Real",
      received: 0.6,
      contributed: 0.38,
      expended: 0.58,
    },
    {
      id: "braganca",
      name: "Bragança",
      received: 0.48,
      contributed: 0.24,
      expended: 0.46,
    },
    {
      id: "porto",
      name: "Porto",
      received: 2.75,
      contributed: 3.25,
      expended: 2.7,
    },
    {
      id: "aveiro",
      name: "Aveiro",
      received: 1.14,
      contributed: 1.32,
      expended: 1.12,
    },
    {
      id: "viseu",
      name: "Viseu",
      received: 0.76,
      contributed: 0.64,
      expended: 0.74,
    },
    {
      id: "guarda",
      name: "Guarda",
      received: 0.44,
      contributed: 0.3,
      expended: 0.42,
    },
    {
      id: "coimbra",
      name: "Coimbra",
      received: 1.02,
      contributed: 0.88,
      expended: 1.0,
    },
    {
      id: "castelo-branco",
      name: "Castelo Branco",
      received: 0.5,
      contributed: 0.36,
      expended: 0.48,
    },
    {
      id: "leiria",
      name: "Leiria",
      received: 0.82,
      contributed: 0.94,
      expended: 0.8,
    },
    {
      id: "santarem",
      name: "Santarém",
      received: 0.72,
      contributed: 0.76,
      expended: 0.7,
    },
    {
      id: "portalegre",
      name: "Portalegre",
      received: 0.38,
      contributed: 0.24,
      expended: 0.36,
    },
    {
      id: "lisboa",
      name: "Lisboa",
      received: 4.05,
      contributed: 4.85,
      expended: 3.98,
    },
    {
      id: "setubal",
      name: "Setúbal",
      received: 1.42,
      contributed: 1.55,
      expended: 1.38,
    },
    {
      id: "evora",
      name: "Évora",
      received: 0.48,
      contributed: 0.34,
      expended: 0.46,
    },
    {
      id: "beja",
      name: "Beja",
      received: 0.44,
      contributed: 0.3,
      expended: 0.42,
    },
    {
      id: "faro",
      name: "Faro",
      received: 1.05,
      contributed: 1.2,
      expended: 1.02,
    },
  ],
  "2018": [
    {
      id: "viana-do-castelo",
      name: "Viana do Castelo",
      received: 0.56,
      contributed: 0.42,
      expended: 0.54,
    },
    {
      id: "braga",
      name: "Braga",
      received: 1.2,
      contributed: 1.34,
      expended: 1.18,
    },
    {
      id: "vila-real",
      name: "Vila Real",
      received: 0.58,
      contributed: 0.36,
      expended: 0.56,
    },
    {
      id: "braganca",
      name: "Bragança",
      received: 0.46,
      contributed: 0.22,
      expended: 0.44,
    },
    {
      id: "porto",
      name: "Porto",
      received: 2.65,
      contributed: 3.15,
      expended: 2.6,
    },
    {
      id: "aveiro",
      name: "Aveiro",
      received: 1.1,
      contributed: 1.28,
      expended: 1.08,
    },
    {
      id: "viseu",
      name: "Viseu",
      received: 0.72,
      contributed: 0.6,
      expended: 0.7,
    },
    {
      id: "guarda",
      name: "Guarda",
      received: 0.42,
      contributed: 0.28,
      expended: 0.4,
    },
    {
      id: "coimbra",
      name: "Coimbra",
      received: 0.98,
      contributed: 0.84,
      expended: 0.96,
    },
    {
      id: "castelo-branco",
      name: "Castelo Branco",
      received: 0.48,
      contributed: 0.34,
      expended: 0.46,
    },
    {
      id: "leiria",
      name: "Leiria",
      received: 0.78,
      contributed: 0.9,
      expended: 0.76,
    },
    {
      id: "santarem",
      name: "Santarém",
      received: 0.68,
      contributed: 0.72,
      expended: 0.66,
    },
    {
      id: "portalegre",
      name: "Portalegre",
      received: 0.36,
      contributed: 0.22,
      expended: 0.34,
    },
    {
      id: "lisboa",
      name: "Lisboa",
      received: 3.85,
      contributed: 4.65,
      expended: 3.78,
    },
    {
      id: "setubal",
      name: "Setúbal",
      received: 1.36,
      contributed: 1.48,
      expended: 1.32,
    },
    {
      id: "evora",
      name: "Évora",
      received: 0.46,
      contributed: 0.32,
      expended: 0.44,
    },
    {
      id: "beja",
      name: "Beja",
      received: 0.42,
      contributed: 0.28,
      expended: 0.4,
    },
    {
      id: "faro",
      name: "Faro",
      received: 1.0,
      contributed: 1.15,
      expended: 0.98,
    },
  ],
}
